# -*- coding: utf-8 -*-
"""calculatetor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CioNfVt6_x6TnUjpFBRNVPYZyXwSbXXa
"""

def menu():
  print("Hello, welcome to the calculator:")
  print("For Binary to Hexadecimal, press 1")
  print("For Hexadecimal to Binary, press 2")
  print("Exit Press 0")

  return input("input your choice: ")

def getBin():
  flag = True
  while flag:
    res = checkBinNumber(input("input your bin number: "))
    if res == False:
      print("Wrong Input , insert again")
    else:
      return res

def checkBinNumber(s):
    for ch in s:
        if ch not in ('0', '1'):
            return False

    if s==None or len(s)==0:
      return False

    return s


def getHex():
  flag = True
  while flag:
    res = checkHexNumber(input("input your Hex number: "))
    if res == False:
      print("Wrong Input , insert again")
    else:
      return res

def checkHexNumber(s):
    hex_digits = "0123456789abcdefABCDEF"
    for ch in s:
        if ch not in hex_digits:
            return False

    if s==None or len(s)==0:
      return False

    return s

def binToHex():
  num = getBin()
  decimal = int(num, 2)
  return hex(decimal)[2:].upper()

def hexToBin():
  num = getHex()
  decimal = int(num, 16)
  return bin(decimal)[2:]



while True:
  flag = menu()
  if flag=='0':
     break

  if flag=='1':
      num = binToHex()
      print (f"the Hex value is : {num}")
  elif flag=='2':
      num = hexToBin()
      print(f"the Bin value is : {num}")
  else:
      print("wrong input broooooo")

